# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Decentralized Climate Foundation
description: >-
  Decentralized Climate Foundation (DCIPs) describe standards for the Decentralized Climate
  platform, including core protocol specifications, client APIs, and contract
  standards.
url: "dcips.decentralizedclimate.org/"
github_username:  DECENTRALIZEDCLIMATE
repository: DECENTRALIZEDCLIMATE/DCIPs

header_pages:
 - all.html
 - core.html
 - networking.html
 - interface.html
 - meta.html
 - informational.html

# Build settings
highlighter: rouge
markdown: kramdown
theme: minima
kramdown:
  math_engine:       mathjax
  parse_block_html:  false
  # This is the default, but be explicit as some DCIPs depend on it
  auto_ids:          true
  # This is to ensure more determistic behaviour
  auto_id_stripping: true
  syntax_highlighter: rouge

permalink: /:slug


collections:
  dcip:
    output: true


defaults:
  -
    scope:
      path: "DCIPs"
    values:
      layout: "dcip"

exclude:
  - .github
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - dcip-template.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - README.md
  
include:
  - LICENSE

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
